FROM maven:3.9.6-openjdk-24 AS build

WORKDIR /application

COPY pom.xml .
COPY mvnw .
COPY .mvn .mvn

RUN chmod +x .mvnw

COPY src ./src

RUN ./mvnw clean package -DskipTests

FROM openjdk:17-jdk-slim
WORKDIR /application

COPY --from=build/application/target/estudante-0.0.1-SNAPSHOT.jar app.jar

EXPOSE 8082
ENTRYPOINT ["java", "-jar", "app.jar"]
